#!/usr/bin/env python

import argparse
import subprocess
import tempfile
import os
import sys

def createAssemblyFile(tmpDir, file, args, polly):
  llFile = tmpDir + '/output.ll'
  preoptFile = tmpDir + '/output.preopt.ll'
  pollyFile = tmpDir + '/output.polly.ll'
  optFile = tmpDir + '/output.opt.ll'
  assemblyFile = tmpDir + '/output.opt.s'

  includeFlags = ['-I' + x for x in args.includes]
  preprocessorFlags = ['-D' + x for x in args.preprocessor]

  # Create .ll file
  commandLine = ["clang","-emit-llvm", "-S", file, '-o', llFile] \
                + includeFlags + preprocessorFlags
  subprocess.call(commandLine, shell=False)

  # Preoptimize it for polly
  preoptPasses = '-basicaa -mem2reg -inline -early-cse -simplify-libcalls ' \
                 '-simplifycfg -instcombine -tailcallelim -loopsimplify ' \
                 '-lcssa -loop-rotate -lcssa -loop-unswitch -instcombine ' \
                 '-loopsimplify -lcssa -indvars -loop-deletion -instcombine ' \
                 '-polly-prepare'

  commandLine = ['opt', '-load', polly] + preoptPasses.split(' ') \
                + ['-S', llFile, '-o', preoptFile]
  subprocess.call(commandLine)


  # Run polly
  if args.fpolly:
    optionalArgs = []

    if args.fpluto:
      optionalArgs = ['-polly-optimize']
    if args.ftile:
      optionalArgs.append('-enable-pluto-tile')

    if args.debug:
      commandLine = ['opt', '-load', polly, '-basicaa'] + optionalArgs \
                    + ['-polly-cloog', '-analyze', preoptFile, '-q', \
                       '-disable-polly-legality']
      subprocess.call(commandLine)
    commandLine = ['opt', '-load', polly, '-basicaa'] + optionalArgs \
                  + ['-polly-codegen', '-S', preoptFile, '-o', pollyFile, \
                     '-disable-polly-legality']
    subprocess.call(commandLine)
  else:
    commandLine = ['cp', preoptFile, pollyFile]
    subprocess.call(commandLine)

  # Optimize it
  commandLine = ['opt', '-O3', '-S', pollyFile, '-o', optFile]
  subprocess.call(commandLine)

  # Create assembly file
  commandLine = ['llc', optFile, '-o', assemblyFile]
  subprocess.call(commandLine)

  return assemblyFile

def parseArguments():
  description = 'pollycc is a simple replacement for compiler drivers like ' \
                'gcc, clang or icc. It uses clang to compile c code and can ' \
                'optimize the code with Polly. It will either produce an ' \
                'optimized binary or an optimized \'.o\' file.'

  parser = argparse.ArgumentParser(description=description)
  parser.add_argument('files', nargs='+')
  parser.add_argument('-o', '--output', help='The name of the output file')
  parser.add_argument('-I', action='append', dest='includes', default=[])
  parser.add_argument('-D', action='append', dest='preprocessor', default=[])
  parser.add_argument('-l', action='append', dest='libraries', default=[])
  parser.add_argument('-L', action='append', dest='librarypath', default=[])
  parser.add_argument('-O', choices='0123s')
  parser.add_argument('-c', action='store_true')
  parser.add_argument('-fpolly', help='Enable polly', action='store_true')
  parser.add_argument('-fpluto', help='Enable pluto', action='store_true')
  parser.add_argument('-ftile', help='Enable pluto tiling', action='store_true')
  parser.add_argument('-d', '--debug', help='Print debugging output',
                      action='store_true')
  parser.add_argument('-v', '--version', dest='version', action='store_true',
                      help='Print version info')
  return parser.parse_args()

def createAssemblyFiles(files, args, pollyLib):
  assemblyFiles = []

  tmpDir = tempfile.mkdtemp(prefix='pollycc-');

  for file in args.files:
    assemblyFiles.append(createAssemblyFile(tmpDir, file, args, pollyLib))

  return assemblyFiles

def createOutputFiles(assemblyFiles, args):
  if args.output:
    outputFile = args.output
  elif len(args.files) == 1 and args.c:
    outputFile = args.files[0].replace('.c', '.o')
  else:
    outputFile = 'a.out'

  linkerFlags = ['-l' + x for x in args.libraries]
  libraryPath = ['-L' + x for x in args.librarypath]

  commandLine = ['gcc', '-o', outputFile] + assemblyFiles

  if args.c:
    commandLine = commandLine + ['-c']
  else:
    commandLine = commandLine + linkerFlags + libraryPath

  subprocess.call(commandLine)

def main():
  args = parseArguments()

  if not 'LIBPOLLY' in os.environ:
    sys.exit('Polly library not provided. Please set LIBPOLLY environment ' + \
             'variable to the LLVMPolly.so file')

  pollyLib = os.environ['LIBPOLLY']

  assemblyFiles = createAssemblyFiles(args.files, args, pollyLib)
  createOutputFiles(assemblyFiles, args)

if __name__ == '__main__':
  main()
