FIND_PATH(CLOOG_INCLUDE_DIR cloog.h PATH_SUFFIXES cloog)

FIND_LIBRARY(CLOOG_LIBRARY NAMES cloog)

IF (CLOOG_INCLUDE_DIR AND CLOOG_LIBRARY)
  SET(CLOOG_FOUND TRUE)
ENDIF (CLOOG_INCLUDE_DIR AND CLOOG_LIBRARY)


IF (CLOOG_FOUND)
  IF (NOT Cloog_FIND_QUIETLY)
    MESSAGE(STATUS "Found Cloog: ${CLOOG_LIBRARY}")
  ENDIF (NOT Cloog_FIND_QUIETLY)
ELSE (CLOOG_FOUND)
  IF (Cloog_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Cloog")
  ENDIF (Cloog_FIND_REQUIRED)
ENDIF (CLOOG_FOUND)

